{{- if not .Values.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "noncer.name" . }}"
type: Opaque
data:
  password: {{ .Values.email.password | required ".Values.email.password is required." | b64enc }}
  webhook: {{ .Values.bot.webhook | required ".Values.bot.webhook is required" | b64enc }}
{{- end -}}